version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing dependencies...
      - apt-get update && apt-get install -y sshpass
  build:
    commands:
      - echo Building the Spring Boot app...
      - mvn clean package -DskipTests
  post_build:
    commands:
      - echo Deploying to EC2...
      # Stop old app
      - sshpass -p "$EC2_PASS" ssh -o StrictHostKeyChecking=no root@$EC2_HOST "pkill -f studentwebapp || true"
      # Copy new jar to EC2
      - sshpass -p "$EC2_PASS" scp -o StrictHostKeyChecking=no target/studentwebapp-0.0.1-SNAPSHOT.jar root@$EC2_HOST:/root/studentwebapp.jar
      # Start the app
      - sshpass -p "$EC2_PASS" ssh -o StrictHostKeyChecking=no root@$EC2_HOST "nohup java -jar /root/studentwebapp.jar > /root/app.log 2>&1 &"
artifacts:
  files:
    - target/studentwebapp-0.0.1-SNAPSHOT.jar
